#!/bin/sh

if ! test -e webhook.py -a "$(hostname)" = 'sd-ssh'; then
    echo "error: please run from the top-level directory in sd-ssh"
    exit 2
fi

runnerDir=/var/lib/sdci-ci-runner
workstationRepo="https://github.com/freedomofpress/securedrop-workstation"

sudo mkdir -p "$runnerDir"
sudo chown user:user "$runnerDir"
cp -a webhook.py "$runnerDir"

test -f "$runnerDir/config.json" || curl -L -o "$runnerDir/config.json" "$workstationRepo/raw/main/files/config.json.example"
test -f "$runnerDir/sd-journalist.sec" || curl -L -o "$runnerDir/sd-journalist.sec" "$workstationRepo/raw/main/sd-journalist.sec.example"

mkdir -p ~/bin
cp -a upload-report cancel.py ~/bin

sudo cp -a sdci-repo-webhook.service /etc/systemd/system

flaskenv="$runnerDir/.flaskenv"
test -e "$flaskenv" || sudo vim "$flaskenv"

sudo systemctl daemon-reload
sudo systemctl enable sdci-repo-webhook
sudo systemctl start sdci-repo-webhook
